compress:
  script:
    - mkdir .temp
    - cp -r * .temp/
    - mv .temp/ gmseofields/
    - zip -r gmseofields.zip gmseofields/
  artifacts:
    paths:
      - gmseofields.zip
    expire_in: 4 week
