# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  zipme:
    runs-on: ubuntu-latest
    steps:
    - name: action-zip
      # You may pin to the exact commit or the version.
      # uses: montudor/action-zip@c25e01d7489d0274569440a2f0281b4569df16bc
      uses: montudor/action-zip@v0.1.1
